/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'counsellingType' : IDL.Text,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
});
export const VoiceSubmission = IDL.Record({
  'id' : IDL.Nat,
  'audioStorageKey' : IDL.Text,
  'name' : IDL.Text,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getVoiceSubmissions' : IDL.Func([], [IDL.Vec(VoiceSubmission)], ['query']),
  'storeContactSubmission' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'storeVoiceSubmission' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'counsellingType' : IDL.Text,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
  });
  const VoiceSubmission = IDL.Record({
    'id' : IDL.Nat,
    'audioStorageKey' : IDL.Text,
    'name' : IDL.Text,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getVoiceSubmissions' : IDL.Func([], [IDL.Vec(VoiceSubmission)], ['query']),
    'storeContactSubmission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'storeVoiceSubmission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };